In [9]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import GridSearchCV #网格搜索
from sklearn.model_selection import train_test_split,KFold #数据集划分，交叉验证
import xgboost as xgb      #xgboost
import warnings
import sklearn

In [10]:
warnings.filterwarnings('ignore')

In [36]:
data_o = pd.read_csv('data.csv')

In [31]:
data_o

,flow,period,workday,blue_rate,yellow_rate,green_rate,other_rate,rate
0,130.0,0,1,0.615385,0.369231,0.007692,0.007692,0.038462
1,109.0,1,1,0.467890,0.513761,0.018349,0.000000,0.100917
2,97.0,2,1,0.659794,0.319588,0.010309,0.010309,0.020619
3,91.0,3,1,0.472527,0.505495,0.010989,0.010989,0.054945
4,103.0,4,1,0.398058,0.601942,0.000000,0.000000,0.038835
...,...,...,...,...,...,...,...,...
3643,164.0,91,1,0.664634,0.310976,0.024390,0.000000,0.152439
3644,122.0,92,1,0.532787,0.459016,0.000000,0.008197,0.155738
3645,136.0,93,1,0.669118,0.301471,0.022059,0.007353,0.088235
3646,137.0,94,1,0.649635,0.291971,0.051095,0.007299,0.124088
3647,120.0,95,1,0.566667,0.400000,0.033333,0.000000,0.200000

In [29]:
int(len(data_o)*0.8)

2918

In [37]:


# index=int(len(data_o)*0.8)

data_o=data_o.sample(frac=1)#数据的随机打散

In [38]:
data_o

,flow,period,workday,blue_rate,yellow_rate,green_rate,other_rate,rate
2047,264.0,31,0,0.678030,0.310606,0.011364,0.000000,0.113636
1226,341.0,74,1,0.771261,0.196481,0.032258,0.000000,0.082111
2527,278.0,31,1,0.733813,0.251799,0.010791,0.003597,0.068345
1986,393.0,66,1,0.778626,0.208651,0.012723,0.000000,0.127226
793,147.0,25,1,0.421769,0.578231,0.000000,0.000000,0.054422
...,...,...,...,...,...,...,...,...
505,149.0,25,1,0.463087,0.523490,0.013423,0.000000,0.060403
1298,329.0,50,1,0.705167,0.270517,0.018237,0.006079,0.088146
668,185.0,92,1,0.648649,0.324324,0.021622,0.005405,0.048649
1229,287.0,77,1,0.714286,0.247387,0.038328,0.000000,0.038328
144,297.0,48,1,0.740741,0.245791,0.013468,0.000000,0.127946

In [43]:
data_o['label']=data_o['rate']

In [46]:
data_o

,flow,period,workday,blue_rate,yellow_rate,green_rate,other_rate,rate
2047,264.0,31,0,0.678030,0.310606,0.011364,0.000000,0.113636
1226,341.0,74,1,0.771261,0.196481,0.032258,0.000000,0.082111
2527,278.0,31,1,0.733813,0.251799,0.010791,0.003597,0.068345
1986,393.0,66,1,0.778626,0.208651,0.012723,0.000000,0.127226
793,147.0,25,1,0.421769,0.578231,0.000000,0.000000,0.054422
...,...,...,...,...,...,...,...,...
505,149.0,25,1,0.463087,0.523490,0.013423,0.000000,0.060403
1298,329.0,50,1,0.705167,0.270517,0.018237,0.006079,0.088146
668,185.0,92,1,0.648649,0.324324,0.021622,0.005405,0.048649
1229,287.0,77,1,0.714286,0.247387,0.038328,0.000000,0.038328
144,297.0,48,1,0.740741,0.245791,0.013468,0.000000,0.127946

In [39]:
data=data_o.iloc[0:index,:]
data

,flow,period,workday,blue_rate,yellow_rate,green_rate,other_rate,rate
2047,264.0,31,0,0.678030,0.310606,0.011364,0.000000,0.113636
1226,341.0,74,1,0.771261,0.196481,0.032258,0.000000,0.082111
2527,278.0,31,1,0.733813,0.251799,0.010791,0.003597,0.068345
1986,393.0,66,1,0.778626,0.208651,0.012723,0.000000,0.127226
793,147.0,25,1,0.421769,0.578231,0.000000,0.000000,0.054422
...,...,...,...,...,...,...,...,...
2907,255.0,27,1,0.678431,0.317647,0.000000,0.003922,0.101961
1142,193.0,86,1,0.626943,0.352332,0.015544,0.005181,0.025907
166,481.0,70,1,0.769231,0.197505,0.029106,0.004158,0.068607
592,65.0,16,1,0.384615,0.584615,0.030769,0.000000,0.000000
2167,324.0,55,0,0.672840,0.302469,0.021605,0.003086,0.157407

In [40]:
data_test=data_o.iloc[index:,:]

In [41]:
data_test

,flow,period,workday,blue_rate,yellow_rate,green_rate,other_rate,rate
518,333.0,38,1,0.690691,0.294294,0.012012,0.003003,0.108108
1890,402.0,66,1,0.768657,0.206468,0.022388,0.002488,0.104478
1947,191.0,27,1,0.607330,0.371728,0.015707,0.005236,0.000000
2568,325.0,72,1,0.753846,0.236923,0.009231,0.000000,0.135385
2058,358.0,42,0,0.784916,0.198324,0.016760,0.000000,0.136872
...,...,...,...,...,...,...,...,...
505,149.0,25,1,0.463087,0.523490,0.013423,0.000000,0.060403
1298,329.0,50,1,0.705167,0.270517,0.018237,0.006079,0.088146
668,185.0,92,1,0.648649,0.324324,0.021622,0.005405,0.048649
1229,287.0,77,1,0.714286,0.247387,0.038328,0.000000,0.038328
144,297.0,48,1,0.740741,0.245791,0.013468,0.000000,0.127946

In [16]:
data

,flow,period,workday,blue_rate,yellow_rate,green_rate,other_rate,rate
3196,238.0,28,1,0.638655,0.352941,0.004202,0.004202,0.105042
3246,251.0,78,1,0.745020,0.231076,0.011952,0.011952,0.131474
626,333.0,50,1,0.720721,0.252252,0.024024,0.003003,0.117117
1824,107.0,0,1,0.485981,0.504673,0.009346,0.000000,0.112150
3372,72.0,12,0,0.430556,0.527778,0.027778,0.013889,0.166667
...,...,...,...,...,...,...,...,...
3457,104.0,1,0,0.576923,0.403846,0.019231,0.000000,0.163462
2900,96.0,20,1,0.531250,0.458333,0.010417,0.000000,0.114583
199,85.0,7,0,0.435294,0.529412,0.011765,0.023529,0.058824
465,267.0,81,1,0.730337,0.254682,0.011236,0.003745,0.026217
1914,208.0,90,1,0.591346,0.384615,0.019231,0.004808,0.115385

In [47]:
train=data

In [48]:
y_train = train['rate']
y_train

2047    0.113636
1226    0.082111
2527    0.068345
1986    0.127226
793     0.054422
          ...
2907    0.101961
1142    0.025907
166     0.068607
592     0.000000
2167    0.157407
Name: rate, Length: 2918, dtype: float64

In [49]:
train.drop(['rate'], axis=1, inplace=True)
train

       flow  period  workday  blue_rate  yellow_rate  green_rate  other_rate
2047  264.0      31        0   0.678030     0.310606    0.011364    0.000000
1226  341.0      74        1   0.771261     0.196481    0.032258    0.000000
2527  278.0      31        1   0.733813     0.251799    0.010791    0.003597
1986  393.0      66        1   0.778626     0.208651    0.012723    0.000000
793   147.0      25        1   0.421769     0.578231    0.000000    0.000000
...     ...     ...      ...        ...          ...         ...         ...
2907  255.0      27        1   0.678431     0.317647    0.000000    0.003922
1142  193.0      86        1   0.626943     0.352332    0.015544    0.005181
166   481.0      70        1   0.769231     0.197505    0.029106    0.004158
592    65.0      16        1   0.384615     0.584615    0.030769    0.000000
2167  324.0      55        0   0.672840     0.302469    0.021605    0.003086

[2918 rows x 7 columns]

In [18]:
#读入数据


train.drop(['rate'], axis=1, inplace=True)

x = train
y = y_train

In [19]:
seed = 7 
test_size = 0.10 
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=test_size, random_state=seed)
model = xgb.XGBRegressor()               
learning_rate = [0.005,0.01,0.05,0.1]   #学习率
n_estimators = [700]
max_depth = [5]
min_child_weight=[6]
gamma=[0]
subsample=[0.4,0.5,0.6,0.7,0.8,0.9,1]
colsample_bytree=[0.5,0.6,0.7,0.8,0.9,1]
# silent=[0]
# nthread=[4]
# param_grid = dict(learning_rate = learning_rate,n_estimators = n_estimators,max_depth=max_depth,min_child_weight=min_child_weight,gamma=gamma,subsample=subsample,colsample_bytree=colsample_bytree,silent=silent,nthread=nthread)#转化为字典格式
param_grid = dict(learning_rate = learning_rate,n_estimators = n_estimators,max_depth=max_depth,min_child_weight=min_child_weight,gamma=gamma,subsample=subsample,colsample_bytree=colsample_bytree)#转化为字典格式

In [20]:
# kflod=KFold(n_splits=5,shuffle=True) #五折交叉验证

In [21]:
print("Begin Train")
grid_search = GridSearchCV(model,param_grid,scoring = 'r2',n_jobs = -1,cv = 5)
#scoring是损失函数类型

Begin Train

In [22]:
grid_result = grid_search.fit(X_train, Y_train)

In [23]:
print("Best: %f using %s" % (grid_result.best_score_,grid_search.best_params_))

means = grid_result.cv_results_['mean_test_score']
params = grid_result.cv_results_['params']
for mean,param in zip(means,params):
    print("%f  with:   %r" % (mean,param))

Best: 0.281212 using {'colsample_bytree': 0.9, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.4}
0.177355  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.4}
0.180746  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.5}
0.182765  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.6}
0.184252  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.7}
0.185136  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.8}
0.187158  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.9}
0.186475  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 1}
0.269230  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.4}
0.271000  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.5}
0.270858  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.6}
0.268442  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.7}
0.271424  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.8}
0.272296  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.9}
0.269060  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 1}
0.173853  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.4}
0.188036  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.5}
0.179956  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.6}
0.181138  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.7}
0.185592  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.8}
0.191567  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.9}
0.200450  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 1}
0.077448  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.4}
0.065951  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.5}
0.078339  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.6}
0.083299  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.7}
0.094503  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.8}
0.113768  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.9}
0.129089  with:   {'colsample_bytree': 0.5, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 1}
0.190097  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.4}
0.192288  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.5}
0.193727  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.6}
0.193664  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.7}
0.193994  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.8}
0.195611  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.9}
0.190023  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 1}
0.277101  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.4}
0.275118  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.5}
0.278942  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.6}
0.274034  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.7}
0.275824  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.8}
0.275586  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.9}
0.266799  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 1}
0.169241  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.4}
0.179862  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.5}
0.179229  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.6}
0.170533  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.7}
0.187438  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.8}
0.193085  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.9}
0.186256  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 1}
0.062617  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.4}
0.084775  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.5}
0.088575  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.6}
0.085266  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.7}
0.093335  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.8}
0.111674  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.9}
0.115319  with:   {'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 1}
0.190097  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.4}
0.192288  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.5}
0.193727  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.6}
0.193664  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.7}
0.193994  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.8}
0.195611  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.9}
0.190023  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 1}
0.277101  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.4}
0.275118  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.5}
0.278942  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.6}
0.274034  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.7}
0.275824  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.8}
0.275586  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.9}
0.266799  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 1}
0.169241  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.4}
0.179862  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.5}
0.179229  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.6}
0.170533  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.7}
0.187438  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.8}
0.193085  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.9}
0.186256  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 1}
0.062617  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.4}
0.084775  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.5}
0.088575  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.6}
0.085266  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.7}
0.093335  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.8}
0.111674  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.9}
0.115319  with:   {'colsample_bytree': 0.7, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 1}
0.195133  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.4}
0.198182  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.5}
0.199019  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.6}
0.197634  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.7}
0.197484  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.8}
0.198351  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.9}
0.193784  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 1}
0.281194  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.4}
0.279109  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.5}
0.278358  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.6}
0.276165  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.7}
0.275702  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.8}
0.273774  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.9}
0.268526  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 1}
0.162082  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.4}
0.171572  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.5}
0.169271  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.6}
0.165457  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.7}
0.170992  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.8}
0.181633  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.9}
0.187389  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 1}
0.066033  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.4}
0.087844  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.5}
0.083586  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.6}
0.096032  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.7}
0.083331  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.8}
0.108627  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.9}
0.122147  with:   {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 1}
0.198783  with:   {'colsample_bytree': 0.9, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.4}
0.200996  with:   {'colsample_bytree': 0.9, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.5}
0.200799  with:   {'colsample_bytree': 0.9, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.6}
0.199810  with:   {'colsample_bytree': 0.9, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.7}
0.199977  with:   {'colsample_bytree': 0.9, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.8}
0.198671  with:   {'colsample_bytree': 0.9, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.9}
0.192469  with:   {'colsample_bytree': 0.9, 'gamma': 0, 'learning_rate': 0.005, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 1}
0.281212  with:   {'colsample_bytree': 0.9, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.4}
0.280323  with:   {'colsample_bytree': 0.9, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.5}
0.277320  with:   {'colsample_bytree': 0.9, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.6}
0.275972  with:   {'colsample_bytree': 0.9, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.7}
0.275421  with:   {'colsample_bytree': 0.9, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.8}
0.272614  with:   {'colsample_bytree': 0.9, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.9}
0.264545  with:   {'colsample_bytree': 0.9, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 1}

In [24]:
res=grid_search.predict(x)

In [25]:
print(grid_result.best_score_)
print(grid_result.best_params_)

0.2812117210165484
{'colsample_bytree': 0.9, 'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 700, 'subsample': 0.4}

In [26]:
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error
import numpy as np 
print(f"均方误差(MSE)：{mean_squared_error(res, y)}")
print(f"根均方误差(RMSE)：{np.sqrt(mean_squared_error(res, y))}")
print(f"绝对误差(RMSE)：{mean_absolute_error(res, y)}")
print(f"测试集R^2：{r2_score(y, res)}")

均方误差(MSE)：0.0011642437856063438
根均方误差(RMSE)：0.03412101677275083
绝对误差(RMSE)：0.026566634652876734
测试集R^2：0.4584152424819603